### ISSUE TITLE
error[E0599]: no method named raw_table_mut found for struct hashbrown::HashMap in the current scope

### ISSUE THREAD

**Issue by rlongland** [dubiousbreakfast/midas-converter#1]
The version of `polars` currently has a bug in its implementation of `hashbrown`. 

As discussed here: https://github.com/pola-rs/polars/issues/19157 there is a fix:

Add the following line to your `Cargo.toml` to resolve the issue by including `hashbrown` with the `raw` feature in your dependencies.

`hashbrown = { version = "0.14.5", features = ["raw"] }`

**Comment by camarsha** [comment]
Thanks, done.
