### ISSUE TITLE
Doesn't seem to work on .mid.lz4 files

### ISSUE THREAD

**Issue by rlongland** [dubiousbreakfast/midas-converter#2]
If I try to run `midas-converter` with the following line:
`midas-converter run00007.mid.lz4 config-file.toml -p`
I get an error:
``thread 'main' panicked at src/main.rs:255:40:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace``
(the backtrace is unhelpful as far as I can tell).

However, if I decompress the file and run on the `run00007.mid` file, `midas-converter` does work. At least it doesn't give me an error...

**Comment by rlongland** [comment]
Update:
I found that it _does_ work if the filename is stripped of the extra dot:
`midas-converter run00007.lz4 config-file.toml -p` works fine if I simply rename the file.

**Comment by camarsha** [comment]
Do you have lz4 installed? It is not mentioned in the README, but to handle the decompression I am just running lz4 and juggling file names, and then cleaning up the file afterwards. I run it on .mid.lz4 all the time, so if lz4 is installed it might be an issue with different versions of lz4 treating the command line flags differently.

**Comment by rlongland** [comment]
Oops! I installed it somewhere between my comments, which explains the strange behaviour. Yes it works on `.mid.lz4` files now that I have lz4 installed.

**Comment by camarsha** [comment]
I really need to catch the case where lz4 does not exist so that the error is more helpful.

**Comment by camarsha** [comment]
So the only thing strange is that the program should have panicked when the lz4 command failed. I added some more error messages, but it is still odd that it got to the point of trying to open a file after the decompression failed. Closing for now.
